### ISSUE TITLE
Seeking backwards by clicking isn't consistent

### ISSUE THREAD

**Issue by NikhilNarayana** [project-slippi/Ishiiruka#116]
Issue found on Windows, not as big of an issue on Linux (tested on Arch, works 99% of the time), unsure about macOS.

During playback the user has three options for seeking backwards, they can press left arrow, hold the seek arrow and drag it back, or click a spot on the seek bar. The third option is not consistent, where sometimes you need to click a few times for it to work.

**Comment by ryanmcgrath** [comment]
Is this one platform-specific? wxWidgets and all that...

**Comment by NikhilNarayana** [comment]
I guess i'm actually not entirely sure. I've only tested this on Windows. I'll update the initial post

**Comment by jordan-zilch** [comment]
From what I can tell, this is caused by a race between two different codepaths which can both change g_playbackStatus->currentPlaybackFrame (it's likely SlippiTimer::Notify() racing with PlaybackSlider::OnSliderClick())

Edit: Actually I'm thinking this is a race between EXI_DeviceSlippi::prepareFrameData() and SlippiPlayback::SeekThread. If you get unlucky, SeekThread will set currentPlaybackFrame before prepareFrameData sets it. We can enforce the order with a CV
