### ISSUE TITLE
Allow users to select from recently connected opponents

### ISSUE THREAD

**Issue by keithrobichaud** [project-slippi/Ishiiruka#125]

**Comment by JLaferri** [comment]
First, Dolphin side you're going to need:
1) Hook into the `CMD_FIND_OPPONENT` handler. When find match is triggered for direct, you'll need to grab the requested connect code and save it to some file probably.
2) Prob best to keep the list unique? So if you get a connect code that has been used before, move it to the front of the list and get rid of the old entry.
3) EXI Handler for new command to fetch a connect code to return to the game, maybe would take an index as an input arg? Something like that

The ASM side is the harder part:
1) You'll need to add an injection into the function at `8023c54c` (NameEntry_Think) to overwrite the input handling for R/L to instead of changing the character page, sending an EXI message to Dolphin to request a tag and then populating that tag.
2) Probably would be good to have a way to quickly clear the current tag and return to entering a new tag. Maybe Z?
3) Would need to add menu text to indicate when R/L can be used to scroll through connect codes. Nice to have would be to hide the R/L displays when pressing the button would do nothing. UI: `<L   [ name entry box ]   R>`

This video might be helpful to start understanding how the ASM modding works:
https://www.youtube.com/watch?v=NOq49h0tkBI

**Comment by Kethku** [comment]
I'm interested in taking a look at this. I'm going to clone and get a build environment for Ishiiruka going.

**Comment by JLaferri** [comment]
@Kethku Fwiw I believe @keithrobichaud is also planning on looking into it. If you want to team up on it, feel free to communicate.

**Comment by Kethku** [comment]
@keithrobichaud I won't step on your tasks. I figured itd be an interesting learning experience. I'd love to be a fly on the wall to learn how this stuff works for a relatively simple feature like this.

**Comment by Kethku** [comment]
An initial draft of step 1 and 2 of dolphin side is done over here: https://github.com/project-slippi/Ishiiruka/pull/134

I'm pretty hazy on the communication between the Dolphin and Assembly side. I'm watching some videos on the channel you linked, but I'm curious if there is any other documentation around that might help me learn how the system works.

A couple questions I have:
1. I think I know how the function injection will work, but I don't know anything about how input handling works. Is there an example in the assembly repo I can try to emulate or at least read to get a better understanding?
2. I think I know where hooking of command handlers is done on the dolphin side, but I seem to remember in the video linked above that the commands are related to the slippi recording format. Is there details I should worry about when adding commands to the list?
3. ... I'll probably have a lot more questions :P

Side note: I chatted with @keithrobichaud on discord and we will be working together. Seems like we're in a similar boat though when it comes to asm knowledge so any help or pointers would be appreciated.

**Comment by CharlesAMiller** [comment]
@Kethku I've actually been working on pretty [similar code](https://github.com/CharlesAMiller/Ishiiruka/tree/feature/recent-opponents-list) for steps 1 and 2. I'm hoping to work more on the assembly side of things soon, and would be up collaborate on the feature with you and @keithrobichaud - provided you're interested in working with more partners. I'm WereHoneyBadger on Discord.

**Comment by Kethku** [comment]
I'm certainly interested in collaborating. I'm not sure how much more help I will be given my complete lack of experience on the asm side of things. I'll send you a message on discord

**Comment by CharlesAMiller** [comment]
Just an update: Kethku and I have mainly been working on the Dolphin portion of the task. It looks like we've mostly completed the first two steps listed in @JLaferri comment above. 

As for the assembly portion, I think I'm at least on the right track for overwriting the [L](https://github.com/CharlesAMiller/slippi-ssbm-asm/blob/feature/recent-opponents-list/Online/Menus/CSS/TextEntryScreen/OnLPress.asm) and [R](https://github.com/CharlesAMiller/slippi-ssbm-asm/blob/feature/recent-opponents-list/Online/Menus/CSS/TextEntryScreen/OnRPress.asm) behavior in Name Entry.
