### ISSUE TITLE
slippi doesn't use native qt theme

### ISSUE THREAD

**Issue by unmellow** [project-slippi/Ishiiruka#313]
## Expected Behavior

slippi should check my environment variables
and see that QT_QPA_PLATFORMTHEME is set to qt5ct
and use the theme i set in that program, this is how dolphin
currently works 

## Current Behavior
slippi is using the default qt light theme with no clear way to change it

## Steps to Reproduce
1. download qt5ct
2. set qt5ct theme to a dark theme. 
3. download slippi appimage
4. open a terminal and type:
```bash 
export QT_QPA_PLATFORMTHEME="qt5ct" (hit enter)
/path/to/Slippi_Online-x86_64.Appimage

```
## Environment
OS:      Manjaro Linux x86_64 
kernel: 5.10.47-1-lts

**Comment by NikhilNarayana** [comment]
Slippi Dolphin is not based on Qt, we use wxWidgets.

**Comment by unmellow** [comment]
Shouldn't it still be using the theme set by gtk or qt? I have both set to dark themes and no matter how I launch it it's white

**Comment by NikhilNarayana** [comment]
I don't have enough knowledge about that to answer confidently. Feel free to ask/search in our Discord's linux support channel.

**Comment by ryanmcgrath** [comment]
Just some context, if it's useful:

- this switched from GTK2 to GTK3 when wxWidgets was bumped some months ago. Unsure if the flag you're after differs with this.
- I wanna say that the build of wxWidgets in Externals has wxQT support, so you could fork and build it yourself that way... it runs on top of QT5 and has its own quirks (been years since I looked at it). It's probably highly unlikely this project would ever use it but if you're building yourself it's something to consider.
